import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Multi-sidebar configuration for Builder and Reference sections
 *
 * - builderSidebar: Usage-focused docs (tutorials, guides, reference)
 *   Canonical source: docs/builder/ (get-started, smart-contracts, etc.)
 *   Ingested content: docs/builder/tutorials/, docs/builder/client/
 *
 * - referenceSidebar: Reference material (protocol, VM, proving)
 *   Canonical source: Landing page in docs/reference/index.md
 *   Ingested content: docs/reference/protocol/, miden-vm/, compiler/, node/
 *
 * ARCHITECTURE NOTE:
 * External docs are ingested at build time via deploy-docs.yml into:
 *   - Reference docs → docs/reference/*
 *   - Builder docs → docs/builder/tutorials/, docs/builder/tools/clients/, docs/builder/tools/note-transport/
 * These paths are cleaned and re-synced on each build from source repos.
 */
const sidebars: SidebarsConfig = {
  builderSidebar: [
    // ── GETTING STARTED
    {
      type: "html",
      value: '<span class="sidebar-section">Getting Started</span>',
    },
    { type: "doc", id: "builder/index" },
    {
      type: "category",
      label: "Get Started",
      link: { type: "doc", id: "builder/get-started/index" },
      items: [{ type: "autogenerated", dirName: "builder/get-started" }],
    },

    // ── BUILD
    {
      type: "html",
      value: '<span class="sidebar-section">Build</span>',
    },
    {
      type: "category",
      label: "Smart Contracts",
      link: { type: "doc", id: "builder/smart-contracts/index" },
      items: [
        "builder/smart-contracts/overview",
        {
          type: "category",
          label: "Rust",
          link: {
            type: "generated-index",
            slug: "/builder/smart-contracts/rust",
            title: "Rust Smart Contracts",
            description: "Rust-first account, note, transaction, type, and composition docs.",
          },
          items: [
            {
              type: "category",
              label: "Accounts",
              link: { type: "generated-index", slug: "/builder/smart-contracts/accounts" },
              items: [
                "builder/smart-contracts/accounts/introduction",
                "builder/smart-contracts/accounts/components",
                "builder/smart-contracts/accounts/storage",
                "builder/smart-contracts/accounts/custom-types",
                "builder/smart-contracts/accounts/account-operations",
                "builder/smart-contracts/accounts/cryptography",
                "builder/smart-contracts/accounts/authentication",
              ],
            },
            {
              type: "category",
              label: "Notes",
              link: { type: "generated-index", slug: "/builder/smart-contracts/notes" },
              items: [
                "builder/smart-contracts/notes/introduction",
                "builder/smart-contracts/notes/note-scripts",
                "builder/smart-contracts/notes/note-types",
                "builder/smart-contracts/notes/reading-notes",
                "builder/smart-contracts/notes/output-notes",
              ],
            },
            {
              type: "category",
              label: "Transactions",
              link: { type: "generated-index", slug: "/builder/smart-contracts/transactions" },
              items: [
                "builder/smart-contracts/transactions/introduction",
                "builder/smart-contracts/transactions/transaction-context",
                "builder/smart-contracts/transactions/transaction-scripts",
                "builder/smart-contracts/transactions/advice-provider",
              ],
            },
            "builder/smart-contracts/cross-component-calls",
            "builder/smart-contracts/types",
            "builder/smart-contracts/patterns",
          ],
        },
        {
          type: "category",
          label: "Miden Standards",
          link: { type: "doc", id: "builder/smart-contracts/standards/index" },
          items: [
            "builder/smart-contracts/standards/account-components",
            "builder/smart-contracts/standards/standard-notes",
            "builder/smart-contracts/standards/faucets-and-policies",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      link: { type: "doc", id: "builder/tutorials/index" },
      items: [
        {
          type: "category",
          label: "Miden Bank",
          link: { type: "doc", id: "builder/tutorials/miden-bank/index" },
          collapsed: true,
          items: [
            // Docusaurus's default numberPrefixParser strips the "00-" style
            // prefix from the doc ID, so files like 00-project-setup.md get
            // the doc ID "project-setup" (and URL slug to match).
            "builder/tutorials/miden-bank/project-setup",
            "builder/tutorials/miden-bank/account-components",
            "builder/tutorials/miden-bank/constants-constraints",
            "builder/tutorials/miden-bank/asset-management",
            "builder/tutorials/miden-bank/note-scripts",
            "builder/tutorials/miden-bank/cross-component-calls",
            "builder/tutorials/miden-bank/transaction-scripts",
            "builder/tutorials/miden-bank/output-notes",
            "builder/tutorials/miden-bank/complete-flows",
          ],
        },
        {
          type: "category",
          label: "Recipes",
          collapsed: true,
          items: [
            {
              type: "category",
              label: "Rust",
              link: { type: "doc", id: "builder/tutorials/recipes/rust/index" },
              collapsed: true,
              items: [
                "builder/tutorials/recipes/rust/counter_contract_tutorial",
                "builder/tutorials/recipes/rust/create_deploy_tutorial",
                "builder/tutorials/recipes/rust/mint_consume_create_tutorial",
                "builder/tutorials/recipes/rust/creating_notes_in_masm_tutorial",
                "builder/tutorials/recipes/rust/custom_note_how_to",
                "builder/tutorials/recipes/rust/unauthenticated_note_how_to",
                "builder/tutorials/recipes/rust/mappings_in_masm_how_to",
                "builder/tutorials/recipes/rust/public_account_interaction_tutorial",
                "builder/tutorials/recipes/rust/foreign_procedure_invocation_tutorial",
                "builder/tutorials/recipes/rust/oracle_tutorial",
                "builder/tutorials/recipes/rust/delegated_proving_tutorial",
                "builder/tutorials/recipes/rust/network_transactions_tutorial",
              ],
            },
            {
              type: "category",
              label: "Web / TypeScript",
              link: { type: "doc", id: "builder/tutorials/recipes/web/index" },
              collapsed: true,
              items: [
                "builder/tutorials/recipes/web/setup_guide",
                "builder/tutorials/recipes/web/counter_contract_tutorial",
                "builder/tutorials/recipes/web/create_deploy_tutorial",
                "builder/tutorials/recipes/web/mint_consume_create_tutorial",
                "builder/tutorials/recipes/web/creating_multiple_notes_tutorial",
                "builder/tutorials/recipes/web/unauthenticated_note_how_to",
                "builder/tutorials/recipes/web/foreign_procedure_invocation_tutorial",
                "builder/tutorials/recipes/web/react_wallet_tutorial",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Development helpers",
          collapsed: true,
          items: [
            { type: "autogenerated", dirName: "builder/tutorials/helpers" },
          ],
        },
        "builder/tutorials/miden_node_setup",
      ],
    },
    {
      type: "category",
      label: "Tools",
      link: { type: "doc", id: "builder/tools/index" },
      items: [
        {
          type: "category",
          label: "Clients",
          link: { type: "doc", id: "builder/tools/clients/index" },
          items: [
            "builder/tools/clients/local-node-testing",
            {
              type: "category",
              label: "Rust",
              link: { type: "doc", id: "builder/tools/clients/rust-client/index" },
              items: [
                "builder/tools/clients/rust-client/install-and-run",
                "builder/tools/clients/rust-client/features",
                "builder/tools/clients/rust-client/design",
                {
                  type: "category",
                  label: "Get started",
                  link: { type: "doc", id: "builder/tools/clients/rust-client/get-started/index" },
                  items: [
                    "builder/tools/clients/rust-client/get-started/create-account-use-faucet",
                    "builder/tools/clients/rust-client/get-started/p2p-public",
                    "builder/tools/clients/rust-client/get-started/p2p-private",
                  ],
                },
                {
                  type: "category",
                  label: "CLI",
                  link: { type: "doc", id: "builder/tools/clients/rust-client/cli/index" },
                  items: [
                    "builder/tools/clients/rust-client/cli/cli-config",
                    "builder/tools/clients/rust-client/cli/cli-troubleshooting",
                  ],
                },
                "builder/tools/clients/rust-client/examples",
                "builder/tools/clients/rust-client/library",
                "builder/tools/clients/rust-client/api-docs",
                // NOTE: debugging.md exists in v0.14.4 (and the v0.14
                // snapshot) but was removed on miden-client's `next`
                // branch. The live /next/ build ingests from `next`,
                // so listing it here would fail sidebar validation.
                // Re-add if a future miden-vNN release brings the page
                // back.
              ],
            },
            {
              type: "category",
              label: "TypeScript",
              link: { type: "doc", id: "builder/tools/clients/web-client/index" },
              items: [
                "builder/tools/clients/web-client/setup",
                "builder/tools/clients/web-client/accounts",
                "builder/tools/clients/web-client/transactions",
                "builder/tools/clients/web-client/notes",
                "builder/tools/clients/web-client/compile",
                "builder/tools/clients/web-client/sync",
                "builder/tools/clients/web-client/testing",
              ],
            },
            {
              type: "category",
              label: "React",
              link: { type: "doc", id: "builder/tools/clients/react-sdk/index" },
              items: [
                "builder/tools/clients/react-sdk/setup",
                "builder/tools/clients/react-sdk/query-hooks",
                "builder/tools/clients/react-sdk/account-state-and-balances",
                "builder/tools/clients/react-sdk/mutation-hooks",
                "builder/tools/clients/react-sdk/advanced",
                "builder/tools/clients/react-sdk/signers",
                "builder/tools/clients/react-sdk/recipes",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Note Transport",
          link: { type: "doc", id: "builder/tools/note-transport/index" },
          items: [
            "builder/tools/note-transport/design",
            "builder/tools/note-transport/operators",
            "builder/tools/note-transport/users",
          ],
        },
        {
          type: "category",
          label: "Bridging",
          link: { type: "doc", id: "builder/tools/bridging/index" },
          items: [
            "builder/tools/bridging/testnet-sandbox",
            "builder/tools/bridging/flows",
            "builder/tools/bridging/api-reference",
          ],
        },
        "builder/tools/midenup",
        "builder/tools/playground",
        "builder/tools/network",
      ],
    },

    // ── SOLUTIONS
    {
      type: "html",
      value: '<span class="sidebar-section">Solutions</span>',
    },
    {
      type: "category",
      label: "Guardian",
      link: { type: "doc", id: "builder/miden-guardian/index" },
      items: [
        {
          type: "category",
          label: "Core Concepts",
          items: [
            "builder/miden-guardian/core-concepts/architecture",
            "builder/miden-guardian/core-concepts/data-structures",
            "builder/miden-guardian/core-concepts/components",
            "builder/miden-guardian/core-concepts/security",
          ],
        },
        {
          type: "category",
          label: "Operator Guide",
          items: [
            "builder/miden-guardian/operator-guide/running",
            "builder/miden-guardian/operator-guide/deployment",
            "builder/miden-guardian/operator-guide/troubleshooting",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Private Multisig",
      link: { type: "doc", id: "builder/private-multisig/index" },
      items: [
        "builder/private-multisig/core-concepts",
        "builder/private-multisig/rust-sdk",
        "builder/private-multisig/typescript-sdk",
      ],
    },

    // ── REFERENCE
    {
      type: "html",
      value: '<span class="sidebar-section">Reference</span>',
    },
    {
      type: "category",
      label: "Migration",
      link: { type: "doc", id: "builder/migration/index" },
      items: [
        "builder/migration/imports-dependencies",
        "builder/migration/hashing-stack",
        "builder/migration/account-changes",
        "builder/migration/note-changes",
        "builder/migration/asset-vault-faucet",
        "builder/migration/transaction-changes",
        "builder/migration/client-changes",
        "builder/migration/masm-changes",
        "builder/migration/vm-assembler",
      ],
    },
    { type: "doc", id: "builder/glossary" },
  ],

  // Reference: landing page + ingested external content
  // Note: External docs are ingested during CI/CD build via deploy-docs.yml
  // For local dev, only the landing page exists; categories appear when content is ingested
  referenceSidebar: [{ type: "autogenerated", dirName: "reference" }],
};

export default sidebars;
